openapi: 3.0.1
info:
  contact:
    email: hello@mainnet.cash
  description: |
    A developer friendly bitcoin cash wallet api

    This API is currently in active development, breaking changes may
    be made prior to official release of version 1.

    **Important:** This library is in active development
  license:
    name: MIT Licence
    url: https://github.com/mainnet-cash/mainnet-js/blob/master/LICENSE
  termsOfService: https://mainnet.cash/terms/
  title: Mainnet Cash
  version: 0.0.1-rc
externalDocs:
  description: Find out more about mainnet-js
  url: https://mainnet.cash
servers:
- description: unstable service (for development)
  url: https://rest-unstable.mainnet.cash/
- description: local development server via npm run serve
  url: http://localhost:3000/v1
tags:
- description: Create a wallet
  externalDocs:
    description: Find out more
    url: http://mainnet.cash/docs#wallet
  name: wallet
paths:
  /wallet/create:
    post:
      operationId: createWallet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletRequest'
        description: Request a new new random wallet
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletResponse'
          description: successful operation
        "405":
          content: {}
          description: Invalid input
      summary: create a new wallet
      tags:
      - wallet
  /wallet/balance:
    post:
      operationId: balance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceRequest'
        description: |
          Request for a wallet balance
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
            text/plain:
              schema:
                description: If a unit of account is passed, a plain number is returned.
                type: number
          description: successful operation
      summary: Get total balance for wallet
      tags:
      - wallet
  /wallet/deposit_address:
    post:
      operationId: depositAddress
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request for a deposit address given a wallet
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepositAddressResponse'
          description: successful operation
      summary: Get a deposit address in cash address format
      tags:
      - wallet
  /wallet/deposit_qr:
    post:
      operationId: depositQr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request for a deposit cash address as a Quick Response code (qrcode)
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScalableVectorGraphic'
          description: "A Qr code image data encoded string in the src field suitable\
            \ for inclusion in html using:\n   - \\<img src\\=\\\"{response.src}\"\
            \\>                \n"
      summary: Get receiving cash address as a qrcode
      tags:
      - wallet
  /wallet/max_amount_to_send:
    post:
      operationId: maxAmountToSend
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaxAmountToSendRequest'
        description: get amount that will be spend with a spend max request. If a
          unit type is specified, a numeric value will be returned.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
        "418":
          content: {}
          description: Invalid network for given address
      summary: Get maximum spendable amount
      tags:
      - wallet
  /wallet/utxo:
    post:
      operationId: utxos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SerializedWallet'
        description: |
          Request detailed list of unspent transaction outputs
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtxoResponse'
          description: successful operation
      summary: Get detailed information about unspent outputs (utxos)
      tags:
      - wallet
  /wallet/send:
    post:
      operationId: send
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendRequest'
        description: place a send request
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
        "418":
          content: {}
          description: Invalid network for given address
      summary: Send some amount to a given address
      tags:
      - wallet
  /wallet/send_max:
    post:
      operationId: sendMax
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMaxRequest'
        description: Request to all available funds to a given address
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMaxResponse'
          description: transaction accepted
        "400":
          content: {}
          description: Invalid Request
      summary: Send all available funds to a given address
      tags:
      - wallet
  /mine:
    post:
      operationId: mine
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MineRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  description: a list of block hashes
                  type: string
                type: array
          description: request accepted
        "400":
          content: {}
          description: Invalid Request
      summary: Mine regtest coins to a specified address
      tags:
      - mine
components:
  schemas:
    Utxo:
      example:
        utxoId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
        unit: sat
        index: 0.8008281904610115
        txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
        value: 100
      properties:
        index:
          type: number
        txId:
          description: The hash of a transaction
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          type: string
        value:
          example: 100
          type: number
        unit:
          description: Unit of account.
          enum:
          - bch
          - usd
          - bit
          - bits
          - sat
          - sats
          - satoshi
          - satoshis
          example: sat
          type: string
        utxoId:
          description: serialized outpoint
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
          type: string
      required:
      - amount
      - txId
      - utxoId
    BalanceRequest:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        unit: sat
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        unit:
          description: Unit of account.
          enum:
          - bch
          - usd
          - bit
          - bits
          - sat
          - sats
          - satoshi
          - satoshis
          example: sat
          type: string
      required:
      - walletId
    BalanceResponse:
      example:
        bch: 1
        sat: 100000000
        usd: 438.02
      properties:
        bch:
          description: Amount in whole Bitcoin Cash
          example: 1
          format: float
          type: number
        sat:
          description: Amount in satoshis
          example: 100000000
          type: integer
        usd:
          description: Amount in United States Dollars
          example: 438.02
          type: number
    ZeroBalanceResponse:
      example:
        bch: 0
        sat: 0
        usd: 0
      properties:
        bch:
          description: Amount in whole Bitcoin Cash
          example: 0
          format: float
          type: number
        sat:
          description: Amount in satoshis
          example: 0
          type: integer
        usd:
          description: Amount in United States Dollars
          example: 0
          type: number
    ScalableVectorGraphic:
      example:
        src: data:image/svg+xml;base64,PD94bWwgdm... ==**
        alt: A Bitcoin Cash Qr Code
        title: bitcoincash:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
      properties:
        src:
          description: "A Qr code image data in svg format as utf-8 encoded string.\n\
            Suitable for inclusion in html using:\n    - \\<img src\\=\\\"**data:image/svg+xml;base64,PD94bWwgdm...\
            \ ==**\"\\>      \n"
          example: data:image/svg+xml;base64,PD94bWwgdm... ==**
          type: string
        title:
          description: hover text for graphic
          example: bitcoincash:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
        alt:
          description: assistive text
          example: A Bitcoin Cash Qr Code
          type: string
    SendMaxRequest:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        cashaddr: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        cashaddr:
          example: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
          type: string
      required:
      - cashaddr
      - walletId
    MaxAmountToSendRequest:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        output_count: 0
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        output_count:
          description: |
            (optional) if sending all funds to multiple addresses, the
            count of the number of address funds will be sent
            to may be included.
          format: int32
          type: integer
      required:
      - walletId
    SerializedWallet:
      discriminator:
        propertyName: walletId
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
      required:
      - walletId
    DepositAddressResponse:
      example:
        cashaddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
      properties:
        cashaddr:
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
    UtxoResponse:
      example:
        utxos:
        - utxoId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
          unit: sat
          index: 0.8008281904610115
          txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          value: 100
        - utxoId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f:0
          unit: sat
          index: 0.8008281904610115
          txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          value: 100
      properties:
        utxos:
          items:
            $ref: '#/components/schemas/Utxo'
          type: array
    WalletResponse:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        cashaddr: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        wif: cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        name: username1
        network: testnet
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        wif:
          description: |
            The wallet in Wallet Import Format (WIF)
          example: cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        name:
          description: User defined string for wallet
          example: username1
          type: string
        cashaddr:
          description: |
            The address in cashaddr format.
          example: bchtest:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
        network:
          description: network type
          enum:
          - mainnet
          - testnet
          - regtest
          - simtest
          example: testnet
          type: string
      type: object
    MineRequest:
      example:
        cashaddr: bchreg:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
        blocks: 105
      properties:
        cashaddr:
          example: bchreg:qpttdv3qg2usm4nm7talhxhl05mlhms3ys43u76rn0
          type: string
        blocks:
          description: the number of blocks to mine
          example: 105
          type: number
    WalletRequest:
      example:
        type: wif
        network: testnet
        name: username1
      properties:
        name:
          description: User defined string for wallet
          example: username1
          type: string
        network:
          description: network type
          enum:
          - mainnet
          - testnet
          - regtest
          - simtest
          example: testnet
          type: string
        type:
          description: Wallet type, either a single wallet with private key (wif)
            or a Hierarchical Deterministic wallet determined from a seed.
          enum:
          - wif
          - hd
          example: wif
          type: string
      type: object
    SendRequest:
      example:
        walletId: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
        to:
        - cashaddr: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
          unit: sat
          value: 100
        - cashaddr: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
          unit: sat
          value: 100
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        to:
          items:
            $ref: '#/components/schemas/SendRequestItem'
          type: array
      type: object
    SerializedSendRequest:
      properties:
        walletId:
          description: |
            ID that is returned in `wallet` field of /wallet call
          example: wif:testnet:cNfsPtqN2bMRS7vH5qd8tR8GMvgXyL5BjnGAKgZ8DYEiCrCCQcP6
          type: string
        to:
          items:
            description: |
              And array of send parameters, in the form:
              [cashaddr, value, unit]
            example: '[bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t, 100, ''sat'']'
            items: {}
            type: array
          type: array
    SendRequestItem:
      example:
        cashaddr: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
        unit: sat
        value: 100
      properties:
        cashaddr:
          example: bchtest:qpalhxhl05mlhms3ys43u76rn0ttdv3qg2usm4nm7t
          type: string
        value:
          example: 100
          type: number
        unit:
          description: Unit of account.
          enum:
          - bch
          - usd
          - bit
          - bits
          - sat
          - sats
          - satoshi
          - satoshis
          example: sat
          type: string
      required:
      - cashaddr
      - unit
      - value
      type: object
    SendMaxResponse:
      example:
        balance:
          bch: 0
          sat: 0
          usd: 0
        txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
      properties:
        txId:
          description: The hash of a transaction
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          type: string
        balance:
          $ref: '#/components/schemas/ZeroBalanceResponse'
      type: object
    SendResponse:
      example:
        balance:
          bch: 1
          sat: 100000000
          usd: 438.02
        txId: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
      properties:
        txId:
          description: The hash of a transaction
          example: 1e6442a0d3548bb4f917721184ac1cb163ddf324e2c09f55c46ff0ba521cb89f
          type: string
        balance:
          $ref: '#/components/schemas/BalanceResponse'
      type: object
